import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import SiteHeader from "@/components/layout/SiteHeader";

const geistSans = localFont({
  variable: "--font-geist-sans",
  src: [
    {
      path: "../fonts/Geist-Variable.woff2",
      style: "normal",
      weight: "100 900",
    },
  ],
  display: "swap",
  fallback: [
    "ui-sans-serif",
    "system-ui",
    "Noto Sans JP",
    "Hiragino Kaku Gothic ProN",
    "Yu Gothic",
    "sans-serif",
  ],
});

const geistMono = localFont({
  variable: "--font-geist-mono",
  src: [
    {
      path: "../fonts/GeistMono-Variable.woff2",
      style: "normal",
      weight: "100 900",
    },
  ],
  display: "swap",
  fallback: [
    "ui-monospace",
    "SFMono-Regular",
    "SFMono-Medium",
    "Menlo",
    "Monaco",
    "Consolas",
    "Liberation Mono",
    "Courier New",
    "monospace",
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col bg-white">
          <SiteHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
